version: '3.7'

services:
    web:
        build:
            context:  ./services/web
            dockerfile: Dockerfile.prod
        command: gunicorn --bind 0.0.0.0:5001 manage:app
        volumes:
            - static_volume:/home/app/web/project/static
        expose:
            - 5001
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./services/nginx
        volumes:
            - static_volume:/home/app/web/project/static
        ports:
            - 5000:80
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
